#!/bin/tcsh
#Must sleep or script fails.
sleep 30

#Please change to the install directories you have chosen.
set config = ~/minetest/minetest/minetest.conf
set world = ~/minetest/minetest/World2
set port = 30000

#Comment this out if you don't want logging feature.
    set index = 1000
    while ( 1 )
        set logfile = ~/minetest/minetest/log/$index.log
        if ( ! -e $logfile ) break
        @ index++
    end

    # Run minetest.
   ~/minetest/minetest/bin/minetestserver --port $port --world $world --config $config >&! $logfile


